/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'markus' at '10/05/14 10:20 PM' with Gradle 1.11
 *
 * @author markus, @date 10/05/14 10:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
